payments=spark.table(f"{catalog}.silver.payments")
payments_validation=(payments
    .withColumn("dq_status",
        when(col("payment_id").isNull()| (col("payment_id")=="") ,"FAIL")
        .when(col("order_id").isNull()| (col("order_id")=="") ,"FAIL")
        .when(col("amount")<0,"FAIL")
        .when(col("transaction_fee")<0,"FAIL")
        .when(col("payment_gateway")=="unknown","FAIL")
        .when(col("payment_status")=="unknown","FAIL")
        .when(col("currency")=="unknown","FAIL")
        .otherwise("PASS"))
    .withColumn("dq_reason",
        when(col("payment_id").isNull()| (col("payment_id")=="") ,"missing_payment_id")
        .when(col("order_id").isNull()| (col("order_id")=="") ,"missing_order_id")
        .when(col("amount")<0,"negative_payment_amount")
        .when(col("transaction_fee")<0,"negative_transaction_fee")
        .when(col("payment_gateway")=="unknown","unknown_gateway")
        .when(col("payment_status")=="unknown","unknown_payment_status")
        .when(col("currency")=="unknown","unknown_currency")
        .otherwise("valid")))
payments_validation.write.format("delta").mode("overwrite").option("overwriteSchema","true").saveAsTable(f"{catalog}.dq.payments_validation")